Project:

  Chess:
  
    dmChessGame:
      name:         Chess Game
      actions:
        play:
  
    dmChessPlayer:
      parent:       dmChessGame
      name:         Chess Player
      front:        false