<?php

/**
 * PluginDmChessQueen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginDmChessQueen extends BaseDmChessQueen
{
  protected function getBasicTargetSquares()
  {
    return array_merge(
      //bishop
      $this->getTargetsByProjection(1, 1),
      $this->getTargetsByProjection(1, -1),
      $this->getTargetsByProjection(-1, 1),
      $this->getTargetsByProjection(-1, -1),
      //rook
      $this->getTargetsByProjection(0, -1),
      $this->getTargetsByProjection(0, 1),
      $this->getTargetsByProjection(-1, 0),
      $this->getTargetsByProjection(+1, 0)
    );
  }

  public function preInsert($event)
  {
    parent::preInsert($event);
    
    if(!$this->y)
    {
      $this->y = $this->Player->isWhite() ? 1 : 8;
    }
  }

}